
// /**
//  * downloadReport
//  * Generates a formatted plain-text medical report and triggers a browser download.
//  *
//  * @param {Object} report
//  * @param {string} report.patientName
//  * @param {string} report.issueSummary
//  * @param {string} report.priorityLevel
//  * @param {string[]} report.recommendations
//  */
// const downloadReport = (report) => {
//   const date = new Date().toLocaleDateString('en-IN', {
//     year: 'numeric',
//     month: 'long',
//     day: 'numeric',
//   });

//   const divider  = '='.repeat(48);
//   const subline  = '-'.repeat(48);

//   const recLines = report.recommendations
//     .map((r, i) => `  ${i + 1}. ${r}`)
//     .join('\n');

//   const content = [
//     divider,
//     '        CARECONNECT — MEDICAL INTERVIEW REPORT',
//     divider,
//     '',
//     `  Date Generated : ${date}`,
//     `  Patient Name   : ${report.patientName}`,
//     `  Priority Level : ${report.priorityLevel}`,
//     '',
//     subline,
//     '  SUMMARY OF ISSUE',
//     subline,
//     `  ${report.issueSummary}`,
//     '',
//     subline,
//     '  KEY RECOMMENDATIONS',
//     subline,
//     recLines,
//     '',
//     divider,
//     '  This report was auto-generated by CareConnect AI.',
//     '  Please review with a qualified healthcare professional.',
//     divider,
//   ].join('\n');

//   const blob     = new Blob([content], { type: 'text/plain;charset=utf-8' });
//   const url      = URL.createObjectURL(blob);
//   const anchor   = document.createElement('a');
//   const safeName = report.patientName.replace(/\s+/g, '-').toLowerCase();

//   anchor.href     = url;
//   anchor.download = `careconnect-report-${safeName}.txt`;
//   document.body.appendChild(anchor);
//   anchor.click();
//   document.body.removeChild(anchor);
//   URL.revokeObjectURL(url);
// };

// export default downloadReport;

/**
 * downloadReport
 * Generates a formatted plain-text medical report and triggers a browser download.
 */
const downloadReport = (report) => {
  const date = new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const W  = 52;
  const eq = '='.repeat(W);
  const ds = '-'.repeat(W);

  const numbered = (arr) =>
    arr && arr.length
      ? arr.map((item, i) => `  ${i + 1}. ${item}`).join('\n')
      : '  None specified';

  const content = [
    eq,
    '        CARECONNECT — MEDICAL INTERVIEW REPORT',
    eq,
    '',
    `  Date Generated : ${date}`,
    `  Patient Name   : ${report.patientName}`,
    `  Priority Level : ${report.priorityLevel}`,
    '',
    ds,
    '  SUMMARY OF ISSUE',
    ds,
    `  ${report.issueSummary}`,
    '',
    ds,
    '  KEY RECOMMENDATIONS',
    ds,
    numbered(report.recommendations),
    '',
    ds,
    "  WHAT YOU SHOULD DO (DO'S)",
    ds,
    numbered(report.dos),
    '',
    ds,
    "  WHAT YOU MUST AVOID (DON'TS)",
    ds,
    numbered(report.donts),
    '',
    ds,
    '  MEDICINES & SUPPLEMENTS',
    ds,
    numbered(report.medicines),
    '',
    eq,
    '  This report was auto-generated by CareConnect AI.',
    '  Please review with a qualified healthcare professional.',
    eq,
  ].join('\n');

  const blob     = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url      = URL.createObjectURL(blob);
  const anchor   = document.createElement('a');
  const safeName = (report.patientName || 'patient').replace(/\s+/g, '-').toLowerCase();

  anchor.href     = url;
  anchor.download = `careconnect-report-${safeName}.txt`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
};

export default downloadReport;